### ISSUE TITLE
Compiler errors on npm install with node 0.12.2 on windows (V8 problem?)

### ISSUE THREAD

**Issue by timknip** [webpack/webpack-dev-server#168]
Windows 8.1 x64
Node 0.12.2

When attempting to install webpack-dev-server 1.8.2 with ```npm install webpack-dev-server``` I get compiler errors.

Typical error:
```error: ‘NewSymbol’ is not a member of ‘v8::String’```

Check out the log [here](http://pastebin.com/edNnt0jB)

The package does get installed into node_modules, but hot-reloading breaks (worked with node 0.10.36).

My guess its latest V8 breaking some stuff.

**Comment by omerts** [comment]
We are also experiencing the same problem, did you manage to solve them?

**Comment by silhouettes** [comment]
+1

**Comment by af7** [comment]
+1 
Any solution to that?

**Comment by davepile** [comment]
+1.
 C:\...\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'       

C:\...\node_modules\webpack-dev-server\node_modules\socket.io-client\node_modules\engine.io-client\node_ modules\ws\node_modules\nan\nan.h(487) : see declaration of 'NanAsyncWorker'

**Comment by claym** [comment]
Similar problems here.

**Comment by stas-webwork** [comment]
+1

**Comment by omaksi** [comment]
+1

**Comment by omaksi** [comment]
For me it was this socket.io issue, the solution was to install ws manually, see: https://github.com/Automattic/socket.io/issues/2057

**Comment by stas-webwork** [comment]
Automattic/socket.io#2057 :+1:

**Comment by codeuniquely** [comment]
Related to 
https://github.com/webpack/webpack-dev-server/issues/195
https://github.com/webpack/webpack-dev-server/issues/191

**Comment by timknip** [comment]
Seems its solved with 1.10.1
