### ISSUE TITLE
TypeError: app.set is not a function - onBeforeSetupMiddleware

### ISSUE THREAD

**Issue by atulgarg22** [webpack/webpack-dev-server#3376]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

app.set is not working after I upgrade to 4.0.0.beta.3. Earlier the code was
```js
// webpack.config.js
    before: async (app, server) => {
      const token = await proxy.fetchOAuthToken();
      app.set("oAuthToken", token.access_token);
    },
```
after upgrade the code is

```js
// webpack.config.js
    onBeforeSetupMiddleware: async (app, server) => {
      const token = await proxy.fetchOAuthToken();
      app.set("oAuthToken", token.access_token);
    },
```

### Please paste the results of `webpack-cli info` here, and mention other relevant information
  System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
    Memory: 8.34 GB / 16.00 GB
  Binaries:
    Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Internet Explorer: 11.0.17763.1852
  Packages:
    case-sensitive-paths-webpack-plugin: ^2.4.0 => 2.4.0
    compression-webpack-plugin: ^8.0.0 => 8.0.0
    eslint-webpack-plugin: ^2.5.4 => 2.5.4
    html-webpack-plugin: ^5.3.1 => 5.3.1
    pnp-webpack-plugin: 1.6.4 => 1.6.4
    terser-webpack-plugin: ^5.1.3 => 5.1.3
    webpack: ^5.38.1 => 5.38.1
    webpack-cli: ^4.7.0 => 4.7.0
    webpack-dev-server: ^4.0.0-beta.3 => 4.0.0-beta.3
    webpack-manifest-plugin: ^3.1.1 => 3.1.1

### Expected Behavior
It should set the token to app

### Actual Behavior
It's giving error TypeError: app.set is not a function
    at Object.onBeforeSetupMiddleware

### For Bugs; How can we reproduce the behavior?
Use the sample code above

**Comment by alexander-akait** [comment]
Our signature:
```
 onBeforeSetupMiddleware: (devServer) => {
      const token = await proxy.fetchOAuthToken();
      devServer.app.set("oAuthToken", token.access_token);
    },
```

**Comment by atulgarg22** [comment]
Thanks a lot Alexander. It helped. Strangely app.use was working in same method but app.set was throwing error. Now with new signature both worked. Many thanks!!
